allowBuilds:
  '@nestjs/core': true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - tmp@0.2.4
  - glob@10.5.0
  - webpack@5.104.1
  - webpack@5.104.0
  - multer@2.1.0
  - ajv@8.18.0
  - multer@2.1.1
  - file-type@21.3.1
  - file-type@21.3.2
  - picomatch@4.0.4
  - '@nestjs/core@11.1.18'
  - uuid@11.1.1
  - qs@6.15.2
overrides:
  '@nestjs/core@<=11.1.17': ^11.1.18
  ajv@>=7.0.0-alpha.0 <8.18.0: ^8.18.0
  file-type@>=13.0.0 <21.3.1: ^21.3.1
  file-type@>=20.0.0 <=21.3.1: ^21.3.2
  glob@>=10.2.0 <10.5.0: ^10.5.0
  multer@<2.1.0: ^2.1.0
  multer@<2.1.1: ^2.1.1
  picomatch@>=4.0.0 <4.0.4: ^4.0.4
  qs@>=6.11.1 <=6.15.1: ^6.15.2
  tmp@<=0.2.3: ^0.2.4
  uuid@<11.1.1: ^11.1.1
  webpack@>=5.49.0 <5.104.0: ^5.104.0
  webpack@>=5.49.0 <=5.104.0: ^5.104.1
